name: Postman Tests

on:
  push:
    branches:
      - main  # Zorg ervoor dat dit de juiste branch is

jobs:
  postman_tests:
    name: Run Postman API Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run Postman collection
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Student App API.json" \
          -e "25436974-c833c679-29df-41a5-9bf4-cf468b06dd2e" --reporters cli,junit
